# Generated by Django 5.1 on 2024-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whoweare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='whoweare/', verbose_name='Who we are image')),
                ('head_title', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Who we are',
                'verbose_name_plural': 'Who we are',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='pricebywaycount',
            options={'verbose_name': 'Car prices by way count', 'verbose_name_plural': 'Cars prices by way count'},
        ),
    ]
