# Generated by Django 5.1 on 2024-08-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_whoweare_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='City name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='City name'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homefirstcontent',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homefirstcontent',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Tour name'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Tour name'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image caption'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image caption'),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='head_title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='head_title_ru',
            field=models.TextField(null=True),
        ),
    ]
