# Generated by Django 5.1 on 2024-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_alter_fleetform_car_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourform',
            name='car_class',
            field=models.CharField(choices=[('any', 'Any'), ('economy', 'Economy'), ('comfort', 'Comfort'), ('business', 'Business'), ('premium', 'Premium'), ('vip', 'VIP'), ('suv', 'SUV'), ('van', 'Van'), ('minibus', 'Minibus'), ('bus', 'Bus')], max_length=255),
        ),
    ]
