# Generated by Django 5.1 on 2024-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_alter_tourform_car_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetform',
            name='country_code',
            field=models.CharField(default=(), max_length=5, verbose_name='Ölkə Kodu'),
            preserve_default=False,
        ),
    ]
