# Generated by Django 5.1 on 2024-10-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_tourform_country_code_alter_fleetform_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetform',
            name='guest_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tourform',
            name='guest_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
