# Generated by Django 5.1 on 2024-11-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_alter_ownerinfo_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobil Nömrə'),
        ),
    ]
