# Generated by Django 4.2.3 on 2024-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0012_alter_ownerinfo_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='section_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='section_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='section_title_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='image',
            field=models.ImageField(upload_to='whoweare/', verbose_name='Şəkil'),
        ),
    ]
