# Generated by Django 4.2.3 on 2024-12-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0013_whoweare_section_title_whoweare_section_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetform',
            name='guest_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourform',
            name='guest_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
